import { test } from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import { PAGE } from '../dist/commands/ui/page.js';

test('identical polling responses preserve queue DOM and do not refetch titles', async () => {
  let writes = 0, reads = 0;
  const element = () => ({ children: [], value: '', set textContent(value) { writes++; this.value = value; }, get textContent() { return this.value; }, append(...nodes) { writes++; this.children.push(...nodes); }, replaceChildren() { writes++; this.children = []; } });
  const nodes = { genSubsteps: element(), queueCount: element(), queueByType: element(), queueItems: element() };
  const context = vm.createContext({ $: id => nodes[id], document: { createElement: element }, api: async () => { reads++; return { content: '# Meeting title' }; } });
  const script = PAGE.match(/<script>([\s\S]*)<\/script>/)[1];
  vm.runInContext(script.slice(script.indexOf('function renderProcessing(s)'), script.indexOf('function watchGenerate()')), context);
  const status = { active: 'source.md', activeTarget: 'social', queue: [{ file: 'source.md', target: 'blog' }], queued: 1, running: true };
  context.renderProcessing(status);
  await Promise.resolve();
  assert.deepEqual(nodes.queueByType.children.map(node => node.children[0].textContent), ['1', '1', '0']);
  assert.equal(nodes.queueByType.children[0].className, 'active');
  const firstRow = nodes.queueItems.children[0];
  status.progress = { current: 1, total: 8, label: 'Drafting social posts' };
  context.renderProcessing(status);
  assert.equal(nodes.genSubsteps.textContent, 'Drafting post 1/8');
  assert.equal(nodes.queueItems.children[0], firstRow);
  status.progress.label = 'Evaluating social posts';
  context.renderProcessing(status);
  assert.equal(nodes.genSubsteps.textContent, 'Evaluating post 1/8');
  writes = 0;
  for (let i = 0; i < 5; i++) context.renderProcessing(structuredClone(status));
  assert.equal(writes, 0);
  assert.equal(reads, 1);
  assert.equal(nodes.queueItems.children[0], firstRow);
  context.renderProcessing({ ...status, activeTarget: 'blog', queue: [], queued: 0 });
  assert.ok(writes > 0);
  assert.deepEqual(nodes.queueByType.children.map(node => node.children[0].textContent), ['0', '1', '0']);
  assert.equal(nodes.queueByType.children[1].className, 'active');
  context.renderProcessing({ ...status, active: null, activeTarget: null, running: false, queue: [], queued: 0 });
  assert.deepEqual(nodes.queueByType.children.map(node => node.children[0].textContent), ['0', '0', '0']);
  assert.ok(nodes.queueByType.children.every(node => node.className === ''));
  assert.equal(reads, 1, 'changed status reuses the cached meeting title');
});

test('diagnostics polling keeps details and table stable while elapsed time changes', async () => {
  let writes=0;
  const element=()=>({value:'',children:[],set textContent(v){writes++;this.value=v;},get textContent(){return this.value;},append(...v){writes++;this.children.push(...v);},replaceChildren(){writes++;this.children=[];},style:{}});
  const nodes={metricsActive:element(),metricsBody:element()};
  const data={sampleSize:0,purposes:[],recent:[],runs:[],active:[{purpose:'blog-draft',elapsedMs:1000,status:'running'}]};
  const context=vm.createContext({$:id=>nodes[id],document:{createElement:element},api:async()=>data});
  const script=PAGE.match(/<script>([\s\S]*)<\/script>/)[1];
  vm.runInContext(script.slice(script.indexOf('const timingLabels'),script.indexOf('let blogPrTimer')),context);
  await context.refreshGenerationMetrics();const table=nodes.metricsBody.children[1];writes=0;
  await context.refreshGenerationMetrics();assert.equal(writes,0);
  data.active[0].elapsedMs=2000;await context.refreshGenerationMetrics();
  assert.equal(writes,1);assert.equal(nodes.metricsBody.children[1],table);
});
